<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Tôi thấy hoa vàng trên cỏ xanh',
                'slug' => 'toi-thay-hoa-vang-tren-co-xanh',
                'description' => 'Tác phẩm văn học thiếu nhi nổi tiếng của nhà văn Nguyễn Nhật Ánh, kể về tuổi thơ đầy kỷ niệm của những đứa trẻ ở một làng quê Việt Nam.',
                'price' => 120000,
                'quantity' => 50,
                'image_url' => 'images/books/toi-thay-hoa-vang-tren-co-xanh.jpg',
                'category_id' => 1,
                'publisher_id' => 1,
                'author_id' => 1,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cô gái đến từ hôm qua',
                'slug' => 'co-gai-den-tu-hom-qua',
                'description' => 'Tiểu thuyết tình cảm tuổi học trò của Nguyễn Nhật Ánh, kể về mối tình đầu trong sáng và đẹp đẽ.',
                'price' => 95000,
                'quantity' => 45,
                'image_url' => 'images/books/co-gai-den-tu-hom-qua.jpg',
                'category_id' => 1,
                'publisher_id' => 2,
                'author_id' => 1,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dế Mèn phiêu lưu ký',
                'slug' => 'de-men-phieu-luu-ky',
                'description' => 'Tác phẩm văn học thiếu nhi kinh điển của Tô Hoài, kể về cuộc phiêu lưu của chú Dế Mèn và những bài học cuộc sống.',
                'price' => 85000,
                'quantity' => 60,
                'image_url' => 'images/books/de-men-phieu-luu-ky.jpg',
                'category_id' => 1,
                'publisher_id' => 1,
                'author_id' => 2,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Chí Phèo',
                'slug' => 'chi-pheo',
                'description' => 'Truyện ngắn nổi tiếng của Nam Cao, kể về số phận bi thảm của Chí Phèo - một nông dân bị tha hóa.',
                'price' => 65000,
                'quantity' => 40,
                'image_url' => 'images/books/chi-pheo.jpg',
                'category_id' => 2,
                'publisher_id' => 3,
                'author_id' => 3,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lão Hạc',
                'slug' => 'lao-hac',
                'description' => 'Truyện ngắn xúc động của Nam Cao về tình cha con và lòng nhân ái của người nông dân Việt Nam.',
                'price' => 55000,
                'quantity' => 35,
                'image_url' => 'images/books/lao-hac.jpg',
                'category_id' => 2,
                'publisher_id' => 3,
                'author_id' => 3,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Số đỏ',
                'slug' => 'so-do',
                'description' => 'Tiểu thuyết châm biếm của Vũ Trọng Phụng, phê phán xã hội thực dân phong kiến Việt Nam đầu thế kỷ XX.',
                'price' => 110000,
                'quantity' => 30,
                'image_url' => 'images/books/so-do.jpg',
                'category_id' => 2,
                'publisher_id' => 3,
                'author_id' => 4,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hà Nội băm sáu phố phường',
                'slug' => 'ha-noi-bam-sau-pho-phuong',
                'description' => 'Tùy bút của Thạch Lam về Hà Nội xưa với những nét đẹp văn hóa và con người thủ đô.',
                'price' => 75000,
                'quantity' => 25,
                'image_url' => 'images/books/ha-noi-bam-sau-pho-phuong.jpg',
                'category_id' => 3,
                'publisher_id' => 3,
                'author_id' => 5,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vang bóng một thời',
                'slug' => 'vang-bong-mot-thoi',
                'description' => 'Tập truyện ngắn của Nguyễn Tuân về những con người tài hoa, nghệ sĩ trong xã hội cũ.',
                'price' => 90000,
                'quantity' => 30,
                'image_url' => 'images/books/vang-bong-mot-thoi.jpg',
                'category_id' => 2,
                'publisher_id' => 3,
                'author_id' => 6,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sóng',
                'slug' => 'song',
                'description' => 'Bài thơ nổi tiếng của Xuân Quỳnh về tình yêu, được coi là một trong những bài thơ tình hay nhất Việt Nam.',
                'price' => 45000,
                'quantity' => 55,
                'image_url' => 'images/books/song.jpg',
                'category_id' => 4,
                'publisher_id' => 3,
                'author_id' => 7,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nhật ký trong tù',
                'slug' => 'nhat-ky-trong-tu',
                'description' => 'Tập thơ của Chủ tịch Hồ Chí Minh viết trong thời gian bị giam cầm ở nhà tù Tưởng Giới Thạch.',
                'price' => 80000,
                'quantity' => 40,
                'image_url' => 'images/books/nhat-ky-trong-tu.jpg',
                'category_id' => 4,
                'publisher_id' => 5,
                'author_id' => 8,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Việt Bắc',
                'slug' => 'viet-bac',
                'description' => 'Bài thơ nổi tiếng của Tố Hữu về chiến khu Việt Bắc trong kháng chiến chống Pháp.',
                'price' => 50000,
                'quantity' => 35,
                'image_url' => 'images/books/viet-bac.jpg',
                'category_id' => 4,
                'publisher_id' => 5,
                'author_id' => 9,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Điêu tàn',
                'slug' => 'dieu-tan',
                'description' => 'Tập thơ đầu tay của Chế Lan Viên, thể hiện tâm trạng buồn bã, cô đơn của thế hệ thanh niên trí thức.',
                'price' => 70000,
                'quantity' => 25,
                'image_url' => 'images/books/dieu-tan.jpg',
                'category_id' => 4,
                'publisher_id' => 3,
                'author_id' => 10,
                'status' => 'activate',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('books')->insert($books);
    }
}
